/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ASpace: typeof import('ant-design-vue/es')['Space']
    BasicBox: typeof import('./components/BasicBox/index.vue')['default']
    BasicHeader: typeof import('./components/BasicHeader/index.vue')['default']
    Loading: typeof import('./components/Loading/index.vue')['default']
    Map: typeof import('./components/Map/index.vue')['default']
    PageWrapper: typeof import('./components/PageWrapper/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScaleScreen: typeof import('./components/scale-screen/scale-screen.vue')['default']
  }
}
